
package gestaopet.view.agendamento.reserva;

import gestaopet.classes.Pet;
import javax.swing.JCheckBox;


public class ItemListPet extends javax.swing.JPanel {

    private Pet pet;
    
    public ItemListPet(Pet pet) {
        initComponents();
        this.pet = pet;
        setItem();
    }

    public void setItem(){
        item0.setText(pet.getNome());
    }
    
    public boolean isSelected(){
        return select.isSelected();
    }
    public Pet petSelected(){
        return pet;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select = new javax.swing.JCheckBox();
        item0 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 35));
        setMinimumSize(new java.awt.Dimension(700, 35));
        setPreferredSize(new java.awt.Dimension(700, 35));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        select.setMargin(new java.awt.Insets(8, 1, 8, 0));
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 34));

        item0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        item0.setText("Item");
        item0.setAlignmentY(0.0F);
        item0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        item0.setIconTextGap(0);
        add(item0, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 1, 300, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel item0;
    private javax.swing.JCheckBox select;
    // End of variables declaration//GEN-END:variables
}
