package gestaopet.view.agendamento.reserva;


import gestaopet.classes.ModalPanel;
import java.awt.Dimension;

public class ShowMessage extends ModalPanel{

    public ShowMessage() {
        //bo = new Blackout(this);
        initComponents();
        Dimension d = new Dimension(265,190);
        setPreferredSize(d);
        setSize(d);
        start();
    }
    
    public void show(String msg){
        show(msg, "Confirmar");
    }
    
    public void show(String msg, String botao){
        msgpanel.setText(msg);
        confirm.setText(botao);
    }
    
    public void confirm(){
        close();
    }

    public void cancel(){
        close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirm = new javax.swing.JButton();
        msgpanel = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        setForeground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(280, 120));
        setMinimumSize(new java.awt.Dimension(280, 120));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirm.setText("Confirmar");
        confirm.setMargin(new java.awt.Insets(0, 0, 0, 0));
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 90, -1));

        msgpanel.setEditable(false);
        msgpanel.setColumns(20);
        msgpanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        msgpanel.setLineWrap(true);
        msgpanel.setRows(5);
        msgpanel.setText("Não foi possível realizar o agendamento para o canil selecionado por indisponibilidade no período escolhido, escolha outro canil e tente novamente.");
        msgpanel.setWrapStyleWord(true);
        msgpanel.setAutoscrolls(false);
        add(msgpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        confirm();
    }//GEN-LAST:event_confirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    public static javax.swing.JTextArea msgpanel;
    // End of variables declaration//GEN-END:variables
}
