package gestaopet.view.New.estoque;

import gestaopet.V;
import gestaopet.classes.Estoque;
import gestaopet.classes.GlobalPanel;
import gestaopet.classes.InputTools;
import java.awt.Color;
import javax.swing.BorderFactory;

public class EstoqueItemList extends GlobalPanel {
    private Estoque estoque;
    
    public EstoqueItemList(Estoque estoque) {
        initComponents();
        this.estoque = estoque; 
        
        editButton.setBackground(Color.white);
        deleteButton.setBackground(Color.white);
        setAll();
    }
    
    public void setAll(){
        produtoLabel.setText(estoque.getProduto());
        categoriaLabel.setText(estoque.getCategoria());
        quantidadeLabel.setText(estoque.getQuantidade() + "");
        valorLabel.setText(InputTools.getStringValor(estoque.getValor())); 
    }
    
    public void openDialog() {
        RemoveItemModal np = new RemoveItemModal(estoque.getIdEstoque());
    }
  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        quantidadeLabel = new javax.swing.JLabel();
        produtoLabel = new javax.swing.JLabel();
        categoriaLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        valorLabel1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel1");

        jButton2.setText("VER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quantidadeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        quantidadeLabel.setText("Quantidade");
        add(quantidadeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 80, 20));

        produtoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        produtoLabel.setText("Produto");
        add(produtoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 20));

        categoriaLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        categoriaLabel.setText("Categoria");
        add(categoriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 120, 20));

        valorLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        valorLabel.setText("Valor");
        add(valorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 10, 90, 20));

        deleteButton.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(204, 0, 153));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/excluir0.png"))); // NOI18N
        deleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 1, true));
        deleteButton.setBorderPainted(false);
        deleteButton.setContentAreaFilled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 100, 40));

        editButton.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(0, 153, 0));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/editar0.png"))); // NOI18N
        editButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        editButton.setBorderPainted(false);
        editButton.setContentAreaFilled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 100, 40));

        valorLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        valorLabel1.setText("R$");
        add(valorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        openDialog();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        V.estoque.updateInput(estoque);
        V.estoque.setMode(true);
        V.nav.setView(12);
    }//GEN-LAST:event_editButtonActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseEvent(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel produtoLabel;
    private javax.swing.JLabel quantidadeLabel;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JLabel valorLabel1;
    // End of variables declaration//GEN-END:variables
}
