package gestaopet.view.reservas;

import gestaopet.DB.ReservaDB;
import gestaopet.classes.DateTools;
import gestaopet.classes.GlobalPanel;
import gestaopet.classes.ModalPanel;
import gestaopet.classes.Pet;
import gestaopet.classes.Reserva;
import gestaopet.components.ImageStore;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class ItemListHome extends GlobalPanel {
    public Reserva reserva;
    public Pet pet;
    private boolean checkin = false;
    private JPanel origin;
    public boolean included = false;
    
    public ItemListHome(Object[] reserva, Pet pet, boolean checkin, JPanel origin) {
        initComponents();
       
        this.reserva = (Reserva)reserva[0];
        this.included = (boolean)reserva[1];
        this.checkin = checkin;
        this.origin = origin;
        this.pet = pet;
        setAll();
    }

    
    public void setAll(){
        setNome();
        setResumo();
        setIcon();
        setPicture();
    }
    
    public void setResumo(){
        String r = DateTools.getDayOfWeek((checkin)? reserva.getCheckin(): reserva.getCheckout());
        resumo.setText(r);
    }
    
    public void setNome(){
        List<Pet> lista = ReservaDB.getIncludes(reserva.getId());


        String includes =(lista.size()>0)? " + "+ lista.size() + " na reserva" : "";
        includes = (this.included)? "Agregado a reserva" :includes ;
        agregados.setText(includes);
        nome.setText(pet.getNome());
    }


    public void setIcon(){
        if(checkin){
            petPict.setBackground(new Color(51,204,0));
        } else {
            petPict.setBackground(new Color(255,51,51));
        }
    }
    
    public void setPicture(){
        ImageStore is = new ImageStore();
        is.openFotoResizer(pet.getFoto(), petPict, 60, 60);
        if(pet.getFoto().equals("none")){
            chekIcon.setIcon(new ImageIcon(getClass().getResource("/gestaopet/tema/icons/minPtImgSilhoute.png")));
        } else {
            chekIcon.setIcon(new ImageIcon(getClass().getResource("/gestaopet/tema/icons/minPtImgPicture.png")));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chekIcon = new javax.swing.JLabel();
        petPict = new javax.swing.JLabel();
        resumo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nome = new javax.swing.JLabel();
        agregados = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chekIcon.setBackground(new java.awt.Color(51, 204, 0));
        chekIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chekIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/minPtImgSilhoute.png"))); // NOI18N
        add(chekIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        petPict.setBackground(new java.awt.Color(51, 204, 0));
        petPict.setOpaque(true);
        add(petPict, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        resumo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        resumo.setForeground(new java.awt.Color(15, 59, 146));
        resumo.setText("(SEG) - 01/01/2023");
        add(resumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 140, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/viewDetails.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 40, 40));

        nome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(15, 59, 146));
        nome.setText("Nome");
        add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 130, 20));

        agregados.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        agregados.setForeground(new java.awt.Color(255, 153, 51));
        agregados.setText("Nome");
        add(agregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 120, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VisualizarReserva vr = new VisualizarReserva(reserva, origin, included);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseEvent(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregados;
    private javax.swing.JLabel chekIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel petPict;
    private javax.swing.JLabel resumo;
    // End of variables declaration//GEN-END:variables
}
