package gestaopet.view.reservas;

import gestaopet.classes.DateTools;
import gestaopet.classes.ModalPanel;
import gestaopet.classes.Reserva;
import java.awt.Color;
import javax.swing.JPanel;

public class ItemList extends javax.swing.JPanel {
    public Reserva reserva;
    private boolean checkin = false;
    private JPanel origin;

    
    public ItemList(Reserva reserva, boolean checkin, JPanel origin) {
        initComponents();
        this.reserva = reserva;
        this.checkin = checkin;
        this.origin = origin;
        setAll();
    }
    
    public void setAll(){
        setResumo();
        setIcon();
        setCanil();
        setAlojamento();
    }
    
    public void setResumo(){
        String r = DateTools.getDayOfWeek((checkin)? reserva.getCheckin(): reserva.getCheckout());
        resumo.setText(r);
    }
    
    
    
    
    
    
    public void setCanil(){
        canil.setText(reserva.getCanil());
    }
    
    public void setAlojamento(){
        alojamento.setText(reserva.getAlojamentoTitle());
    }
    
    public void setIcon(){
        if(checkin){
            chekIcon.setBackground(new Color(204,255,0));
        } else {
            chekIcon.setBackground(new Color(255,51,51));
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chekIcon = new javax.swing.JLabel();
        canil = new javax.swing.JLabel();
        resumo = new javax.swing.JLabel();
        alojamento = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chekIcon.setBackground(new java.awt.Color(204, 255, 0));
        chekIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chekIcon.setText("Icon");
        chekIcon.setOpaque(true);
        add(chekIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 34, 34));

        canil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        canil.setText("CANIL 00");
        add(canil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 5, 70, 30));

        resumo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        resumo.setText("(SEG) - 01/01/2023");
        add(resumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 5, 140, 30));

        alojamento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        alojamento.setText("A00");
        add(alojamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 5, 30, 30));

        jButton1.setText("VER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 5, 80, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VisualizarReserva vr = new VisualizarReserva(reserva, origin, true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alojamento;
    private javax.swing.JLabel canil;
    private javax.swing.JLabel chekIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel resumo;
    // End of variables declaration//GEN-END:variables
}
