package gestaopet.tema.scroll;

import java.awt.Dimension;
import javax.swing.JScrollPane;


public class SpecialScroll extends javax.swing.JPanel {
    private int clickedY = 0;
    private JScrollPane scroll;
    private float h = 0;
    private int he = 0;
    private int adjustX = 0;
    private int adjustY = 0;    
    private int y = 0;
    private int yI = 0;
    private int scroolMax = 0;
    private float iCor = 0;
    private boolean o = false;
 
    
    public SpecialScroll(JScrollPane origin) {
        initComponents();
        scroll = origin;
        updateSize();
        setVisible(true);
        icon.setLocation(-1, 0); 
        origin.setVisible(true);
        origin.getVerticalScrollBar().setVisible(false);
        origin.setVerticalScrollBarPolicy(origin.VERTICAL_SCROLLBAR_NEVER);
    }

    public void clicked(boolean clicked, java.awt.event.MouseEvent evt){ 
        if(clicked){updateScroolMax();}
        clickedY = evt.getY();
    }
    
    public void updateSize(){
        int a = (scroll.getHeight() > 0)? 5 : 0;
        Dimension d = new Dimension(24,scroll.getHeight() +a);
        Dimension d3 = new Dimension(8,scroll.getSize().height-16);
        setSize(d);
        setPreferredSize(d);
        center.setSize(d3);
        center.setPreferredSize(d3);
        center.setLocation(center.getX(), 8);
        int x = scroll.getX() + scroll.getWidth();
        setLocation(x + adjustX, scroll.getY() + adjustY);
        Dimension d2 = new Dimension(scroll.getSize().width,scroll.getSize().height);
        scroll.setSize(d2);
        scroll.setPreferredSize(d2);
        
    }
    
    public void setAdjust(int x, int y){
        adjustX = x;
        adjustY = y;
    }
    
    
    public void updateScroolMax(){
        int restore = scroll.getVerticalScrollBar().getValue();
        scroll.getVerticalScrollBar().setValue(999999999);
        scroolMax = scroll.getVerticalScrollBar().getValue();
        scroll.getVerticalScrollBar().setValue(restore);
    }
    
    public void action(java.awt.event.MouseEvent evt){
        int y = 0;
        y = evt.getYOnScreen()- 1 - clickedY - scroll.getLocationOnScreen().y;
        y = (y <= 0)? 0: y;
        scroll.getVerticalScrollBar().setValue(transpose(y, false));
        setIconLocation(transpose(scroll.getVerticalScrollBar().getValue(), true));
    }


    public void scroolAction(int evt){
        if(evt <= 3){updateScroolMax();}
        setIconLocation(transpose(evt, true));
    }

    public int transpose(int evt, boolean isScrool){
        int output = 0;
        if(isScrool){
            output = (int)((( 3 *(float)scroll.getHeight())/ (float)scroolMax) * evt/3);
        } else {
            output = (int)(((float)scroolMax * evt) / (float)scroll.getHeight());
        }
        return output;
    }
    
    public void setIconLocation(int o){
        o = (o <= 0)? 0: o;
        o = (o >= scroll.getHeight()-20)? scroll.getHeight()-20: o;

        icon.setLocation(icon.getX(), o);
    }

    public void resetPosition(){
        setLocation(0,0);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        center = new javax.swing.JPanel();

        setBackground(new java.awt.Color(237, 245, 255));
        setMinimumSize(new java.awt.Dimension(20, 410));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(20, 410));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/trueEnable.png"))); // NOI18N
        icon.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        icon.setAlignmentY(0.0F);
        icon.setIconTextGap(0);
        icon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                iconMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                iconMouseMoved(evt);
            }
        });
        icon.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                iconMouseWheelMoved(evt);
            }
        });
        icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                iconMouseReleased(evt);
            }
        });
        add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 50, 22));

        center.setBackground(new java.awt.Color(153, 204, 255));
        add(center, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 6, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void iconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMouseReleased
        clicked(false, evt);
    }//GEN-LAST:event_iconMouseReleased

    private void iconMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMouseMoved

    }//GEN-LAST:event_iconMouseMoved

    private void iconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMousePressed
        clicked(true, evt);
    }//GEN-LAST:event_iconMousePressed

    private void iconMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMouseDragged
        action(evt);
    }//GEN-LAST:event_iconMouseDragged

    private void iconMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_iconMouseWheelMoved

    }//GEN-LAST:event_iconMouseWheelMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel center;
    private javax.swing.JLabel icon;
    // End of variables declaration//GEN-END:variables
}
