
package gestaopet.view.pet;

import java.awt.Color;
import javax.swing.JRadioButton;

public class ItemListPessoa extends javax.swing.JPanel {
    private int id;
    private String nome;

    public ItemListPessoa() {
        initComponents();
    }

    public void setItem(Object nome){
        this.nome = (String)nome;
        item0.setText(this.nome);
    }
    public JRadioButton getRadioButton(){
        return select;
    }
    
    public Object[] getSelected(){
        return new Object[] {this.id, this.nome};
    }
    
    public void setId(Object id){
        this.id = (int)id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select = new javax.swing.JRadioButton();
        item0 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 35));
        setMinimumSize(new java.awt.Dimension(700, 35));
        setPreferredSize(new java.awt.Dimension(700, 35));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        select.setContentAreaFilled(false);
        select.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectItemStateChanged(evt);
            }
        });
        add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 35));

        item0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        item0.setText("Item");
        item0.setAlignmentY(0.0F);
        item0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        item0.setIconTextGap(0);
        add(item0, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 1, 300, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void selectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectItemStateChanged
        if(select.isSelected()){
            setBackground(Color.GRAY);
        } else {
            setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_selectItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel item0;
    private javax.swing.JRadioButton select;
    // End of variables declaration//GEN-END:variables
}
