package gestaopet.view.pet;

import gestaopet.view.pet.ItemListPessoa;
import gestaopet.V;
import gestaopet.classes.Pessoa;
import gestaopet.components.modal.Modal;
import gestaopet.enums.PersonMode;
import java.awt.Dimension;
import javax.swing.ScrollPaneConstants;

public class ListarPessoa extends javax.swing.JPanel {
    private java.util.List<Pessoa> localList;
    private Modal parent;
    
    
    public ListarPessoa(java.util.List<Pessoa> list) {
        initComponents();
        this.localList = list;
        setPreferredSize(new Dimension(400, 420));
        setSize(new Dimension(400, 420));
        scroll.setLocation(0, 0);
        scroll.setPreferredSize(new Dimension(380, 300));
        scroll.setSize(new Dimension(380, 300));
        scroll.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        parent = V.newPopUp(this);
        loadList("");
    }
    
    public void loadList(String filter){
        panel.removeAll();
        int y = 5;
        int j = 0;
        for(int i = 0; i < localList.size(); i++){
            String v = localList.get(i).getNome1() + " " + localList.get(i).getNome2();
            if(v.toLowerCase().indexOf(filter.toLowerCase()) > -1 || filter.equals("")){
                j++;
                ItemListPessoa f = new ItemListPessoa();
                select.add(f.getRadioButton());
                f.setItem(localList.get(i).getNome1() + " " + localList.get(i).getNome2());
                f.setId(localList.get(i).getId());
                panel.add(f);
                f.setVisible(true);
                f.setLocation(0, y);
                f.setPreferredSize(new Dimension(325,35));
                f.setSize(new Dimension(325,35));
                y = y + 35;
                Dimension d = new Dimension(350, y);
                panel.setPreferredSize(d);
                panel.setSize(d);
            }
            panel.repaint();
            panel.revalidate();
        }   
        if( j == 0){
            setAlert("Nenhum cadastro encontrado para o termo : " + filter);
        } else {
            setAlert("");
        } 
    }
    
    public void setAlert(String msg){
        alert.setText(msg);
    }

    public void confirm(){
        V.petReg.setDono((int)getSelected()[0], (String)getSelected()[1]);
        parent.close();
    }
    
    public void cancel(){
        parent.close();
    }
    
    public Object[] getSelected(){
        for(int i = 0; i < select.getButtonCount(); i ++){
            ItemListPessoa f = (ItemListPessoa)panel.getComponents()[i];
            if(f.getRadioButton().isSelected()){
                return f.getSelected();
            }
        }
        return null;
    }
    
    public void newPerson(){
        
        V.pessoaReg.setMode(PersonMode.CLIENTE);
        V.pessoaReg.newPersonFromPet();
        parent.close();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select = new javax.swing.ButtonGroup();
        scroll = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        buttonsPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        alert = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.setAutoscrolls(true);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        scroll.setViewportView(panel);

        add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 220));

        search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 5, 270, 40));

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 5, 90, 40));

        buttonsPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buttonsPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 128, 45));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Confirmar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        buttonsPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 19, 128, 45));
        buttonsPanel.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 31, -1, -1));

        add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 390, -1));

        alert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alert.setForeground(new java.awt.Color(204, 0, 0));
        alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 370, 20));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Novo Cadastro");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 50, 375, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        loadList(search.getText());
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        confirm();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cancel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        newPerson();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchButton;
    private javax.swing.ButtonGroup select;
    // End of variables declaration//GEN-END:variables
}
