package gestaopet.components.modal;

import gestaopet.GestaoPet;
import gestaopet.V;
import gestaopet.classes.ModalPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JPanel;

public class Blackout extends JPanel {
    private SpecialModal parent;
    private ModalPanel modal;
    public Blackout(ModalPanel modal) {
        this.modal = modal;
        initComponents();
        Dimension d = new Dimension(Window.getWindows()[0].getSize()/*gestaopet.init.getSize()*/);
        setPreferredSize(d);
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        parent = V.newSpecialModal(this, false);
        setBackground(new Color(0, 0, 0, 130));
        parent.setBackground(new Color(0,0,0,0));
    }
    
    public void onClick(){
        modal.bringToFront();
    }
    public void close(){
        this.parent.close();
    }
    
    public void show(boolean show){
        parent.setVisible(show);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        onClick();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        onClick();
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
