package gestaopet.view.servicos;

import gestaopet.DB.ServicoDB;
import gestaopet.V;
import gestaopet.classes.DateTools;
import gestaopet.classes.InputTools;
import gestaopet.classes.Servico;
import gestaopet.enums.Servicos;
import java.awt.Dimension;
import java.util.Date;
import gestaopet.components.DataPicker;

public class EditarServico extends gestaopet.classes.ModalPanel {
    private Servico s;
    private DataPicker dp;
    
    
    public EditarServico(Servico s) {
        this.s = s;
        initComponents();
                Dimension d = new Dimension(290, 360);
        setPreferredSize(d);
        setSize(d);
        start();
        onLoad();
    }
    
    public void onLoad(){
        setServico();
        setDataHora();
        setSituacao();
        setValor();
    }
    
    public void setServico(){
        switch(s.getServico()){
            case "creche":
                crecheOp.setSelected(true);
                break;
            case "banho":
                banhoOp.setSelected(true);
                break;
            case "banhoetosa":
                banhoTosaOp.setSelected(true);
                break;
        }
    }
    
    public void setSituacao(){
        
        if(s.isSituacao()){
            situacao.setText("Lançado em financeiro");
            valor.setEnabled(false);
        } else {
            situacao.setText("Não lançado em financeiro");
        }
    }
    
    public void setValor(){
        valor.setText(s.getStringValor().replace(".", ","));
    }
    
    public void setDataHora(){
        String a = DateTools.dateToString(s.getData());
        String b = DateTools.timeToString(s.getData());
        
        data.setText(a);
        hora.setText(b);
    }
    
    
    public void save(){
        s.setServico(servicoGroup.getSelection().getActionCommand());
        s.setData(DateTools.stringToDate(data.getText(), hora.getText()));
        //s.setSituacao(situacao.isSelected());
        s.setValor(Double.parseDouble(valor.getText().replace(",", ".")));
        
        ServicoDB.update(s);
        V.serv.filter();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        servicoGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        painel = new javax.swing.JPanel();
        situacao = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        banhoTosaOp = new javax.swing.JRadioButton();
        banhoOp = new javax.swing.JRadioButton();
        crecheOp = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 59, 146));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Agendamento de Serviço");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 280, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/salvarP0.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 110, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/cancelarP0.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 40));

        painel.setOpaque(false);

        situacao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        situacao.setForeground(new java.awt.Color(15, 59, 146));
        situacao.setText("situacao");

        valor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        valor.setForeground(new java.awt.Color(15, 59, 146));
        valor.setText("0,00");
        valor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 59, 146)));
        valor.setCaretColor(new java.awt.Color(15, 59, 146));
        valor.setMargin(new java.awt.Insets(0, 5, 0, 0));
        valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(15, 59, 146));
        jLabel2.setText("R$");

        data.setEditable(false);
        data.setBackground(new java.awt.Color(255, 255, 255));
        data.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        data.setForeground(new java.awt.Color(15, 59, 146));
        data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data.setText("31/12/2222");
        data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 59, 146)));
        data.setCaretColor(new java.awt.Color(15, 59, 146));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dataMouseReleased(evt);
            }
        });
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });

        hora.setEditable(false);
        hora.setBackground(new java.awt.Color(255, 255, 255));
        hora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        hora.setForeground(new java.awt.Color(15, 59, 146));
        hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hora.setText("00:00");
        hora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 59, 146)));
        hora.setCaretColor(new java.awt.Color(15, 59, 146));

        banhoTosaOp.setBackground(new java.awt.Color(255, 255, 255));
        servicoGroup.add(banhoTosaOp);
        banhoTosaOp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        banhoTosaOp.setForeground(new java.awt.Color(15, 59, 146));
        banhoTosaOp.setText("Banho & Tosa");
        banhoTosaOp.setActionCommand("banhoetosa");

        banhoOp.setBackground(new java.awt.Color(255, 255, 255));
        servicoGroup.add(banhoOp);
        banhoOp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        banhoOp.setForeground(new java.awt.Color(15, 59, 146));
        banhoOp.setText("Banho");
        banhoOp.setActionCommand("banho");

        crecheOp.setBackground(new java.awt.Color(255, 255, 255));
        servicoGroup.add(crecheOp);
        crecheOp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        crecheOp.setForeground(new java.awt.Color(15, 59, 146));
        crecheOp.setText("Creche");
        crecheOp.setActionCommand("creche");

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(banhoTosaOp)
                                    .addComponent(banhoOp)
                                    .addComponent(crecheOp)))
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)
                                .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(banhoTosaOp))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(banhoOp))
                    .addComponent(crecheOp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(situacao)
                .addContainerGap())
        );

        add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed

    }//GEN-LAST:event_dataActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorKeyTyped
        valor.setText(InputTools.makeDecimal(valor.getText(), evt, evt.getKeyChar()+""));
        evt.consume();
    }//GEN-LAST:event_valorKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        save();
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseReleased
        try {
            dp.show(true);
        } catch (Exception e) {
            dp = new DataPicker(data);
        }
        dp.setInput(DateTools.dateToString(s.getData()));
    }//GEN-LAST:event_dataMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton banhoOp;
    private javax.swing.JRadioButton banhoTosaOp;
    private javax.swing.JRadioButton crecheOp;
    private javax.swing.JTextField data;
    private javax.swing.JTextField hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel painel;
    private javax.swing.ButtonGroup servicoGroup;
    private javax.swing.JLabel situacao;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
