package gestaopet.view.servicos;

import gestaopet.classes.DateTools;
import gestaopet.classes.GlobalPanel;
import gestaopet.classes.Servico;


public class ItemList extends GlobalPanel {
    private Servico s;
    private EditarServico se;
    private PainelServico servicos;
    //private ListarServico servicosListar;
            
    public ItemList(Servico s, PainelServico servicos) {
        initComponents();
        this.s = s;
        this.servicos = servicos;
        setServico();
    }
/*
    public ItemList(Servico s, ListarServico servicos) {
        initComponents();
        this.s = s;
        this.servicosListar = servicos;
        setServico();
    }*/

    public void excluir(){
        servicos.setIdServico(s.getId());
        servicos.deleteConfirmation();
    }
    
    public void setServico(){
        servico.setText(s.getServicoString());
        data.setText(DateTools.dateToString(s.getData()));
        hora.setText(DateTools.timeToString(s.getData()));
        valor.setText((s.getStringValor().replace(".", ",")));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        hora = new javax.swing.JLabel();
        servico = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Editar");
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 5, 50, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Excluir");
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 5, 50, 30));

        hora.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        hora.setText("HH:MM");
        add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 40, 30));

        servico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        servico.setText("servico");
        servico.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        servico.setAlignmentY(0.0F);
        servico.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        servico.setIconTextGap(0);
        add(servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -3, 100, 20));

        valor.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        valor.setText("00,00");
        add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 10, 110, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jLabel4.setText("R$");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 30, 30));

        data.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        data.setText("dd/mm/aaaa");
        add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, 30));

        jLabel1.setBackground(new java.awt.Color(51, 204, 0));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setMaximumSize(new java.awt.Dimension(34, 34));
        jLabel1.setMinimumSize(new java.awt.Dimension(34, 34));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(35, 35));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 3, 34, 34));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseEvent(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed
        
    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        try {
            se.show(true);
        } catch (Exception e) {
            se = new EditarServico(s);
        }
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        servicos.setIdServico(s.getId());
        servicos.deleteConfirmation();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel data;
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel servico;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
