package gestaopet.view.servicos;

import gestaopet.classes.DateTools;
import gestaopet.classes.GlobalPanel;
import gestaopet.classes.Pet;
import gestaopet.classes.Servico;
import gestaopet.components.ImageStore;
import java.awt.Color;
import javax.swing.ImageIcon;


public class ItemListHome extends GlobalPanel {
    private Servico s;
    private Pet pet;
    private EditarServico se;
    private PainelServico servicos;
            
    public ItemListHome(Servico s, Pet pet, PainelServico servicos) {
        initComponents();
        this.s = s;
        this.servicos = servicos;
        this.pet = pet;
        setServico();
        excluir.setVisible(false);
    }
    
    public void setIcon(){
        
        switch(s.getServico()){
            case "banho":
                view.setIcon(new ImageIcon(getClass().getResource("/gestaopet/tema/icons/banho.png")));
                view2.setIcon(new ImageIcon(getClass().getResource("/gestaopet/tema/icons/banho.png")));
                break;
            case "banhoetosa":
                view.setIcon(new ImageIcon(getClass().getResource("/gestaopet/tema/icons/banhoetosa.png")));
                view2.setIcon(new ImageIcon(getClass().getResource("/gestaopet/tema/icons/banhoetosa.png")));
                break;
            case "creche":
                view.setIcon(new ImageIcon(getClass().getResource("/gestaopet/tema/icons/creche.png")));
                view2.setIcon(new ImageIcon(getClass().getResource("/gestaopet/tema/icons/creche.png")));
                break;
        }
    }

    
    public void setServico(){
        nome.setText(pet.getNome());
        data.setText(DateTools.dateToString(s.getData()));
        hora.setText(DateTools.timeToString(s.getData()));
        setPicture();
        setIcon();
    }
    
    public void setViewLocation(){
        view.setLocation(60, 10);
        
        repaint();
        revalidate();
    }
    
    public void setPicture(){
        ImageStore is = new ImageStore();
        is.openFotoResizer(pet.getFoto(), petPict, 60, 60);
        if(pet.getFoto().equals("none")){
            chekIcon.setIcon(new ImageIcon(getClass().getResource("/gestaopet/tema/icons/minPtImgSilhoute.png")));
        } else {
            chekIcon.setIcon(new ImageIcon(getClass().getResource("/gestaopet/tema/icons/minPtImgPicture.png")));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hora = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        chekIcon = new javax.swing.JLabel();
        petPict = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        view2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hora.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        hora.setText("HH:MM");
        add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 40, 30));

        nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(15, 59, 146));
        nome.setText("servico");
        nome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        nome.setAlignmentY(0.0F);
        nome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nome.setIconTextGap(0);
        add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 100, 20));

        data.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        data.setText("dd/mm/aaaa");
        add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 80, 30));

        chekIcon.setBackground(new java.awt.Color(51, 204, 0));
        chekIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chekIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/minPtImgSilhoute.png"))); // NOI18N
        add(chekIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        petPict.setBackground(new java.awt.Color(102, 204, 255));
        petPict.setOpaque(true);
        add(petPict, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        view.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        view.setBorderPainted(false);
        view.setContentAreaFilled(false);
        view.setMargin(new java.awt.Insets(0, 0, 0, 0));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 40));

        excluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        excluir.setForeground(new java.awt.Color(255, 255, 255));
        excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/delete.png"))); // NOI18N
        excluir.setText("X");
        excluir.setBorderPainted(false);
        excluir.setContentAreaFilled(false);
        excluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluir.setIconTextGap(0);
        excluir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        add(excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, 40));

        view2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        view2.setBorderPainted(false);
        view2.setContentAreaFilled(false);
        view2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2ActionPerformed(evt);
            }
        });
        add(view2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseEvent(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseEntered

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        try {
            se.show(true);
        } catch (Exception e) {
            se = new EditarServico(s);
        }
    }//GEN-LAST:event_viewActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        servicos.setIdServico(s.getId());
        servicos.deleteConfirmation();
    }//GEN-LAST:event_excluirActionPerformed

    private void view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2ActionPerformed
        try {
            se.show(true);
        } catch (Exception e) {
            se = new EditarServico(s);
        }
    }//GEN-LAST:event_view2ActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chekIcon;
    private javax.swing.JLabel data;
    public javax.swing.JButton excluir;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel petPict;
    public javax.swing.JButton view;
    public javax.swing.JButton view2;
    // End of variables declaration//GEN-END:variables
}
