package gestaopet.view.pessoa;

import gestaopet.DB.PessoaDB;
import gestaopet.V;
import gestaopet.classes.FunctionButton;
import gestaopet.classes.GlobalPanel;
import gestaopet.classes.Pessoa;
import gestaopet.tema.scroll.SpecialScroll;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;

public class ListarPessoa extends GlobalPanel {
    private FunctionButton[] bList;
    private String param;
    private String tipo;
    private List<Pessoa> personList = new ArrayList<>();
    private SpecialScroll ss;
    
    public ListarPessoa(int param) {
        initComponents();
        this.param = param + "";
        
        ss = new SpecialScroll(entityPanel);
        scroll.add(ss);
        ss.resetPosition();
        //ss.setAdjust(-150, 85);
        
        
        FunctionButton[] ini = {
            new FunctionButton("", true,"novo1.png", this.param),
            //new FunctionButton("Editar", false,"icons8_edit_property_35px.png", this.param),
            new FunctionButton("Voltar", true,"icons8_left_2_35px.png", this.param)};
        buttonsInit(ini);
        //loadPersonList("");
    }
  
    @Override
    public void action(ActionEvent evt){
        switch(evt.getActionCommand()){
            case "b1" :     //salvar
                V.pessoaReg.openDialog();
                break;      //Voltar
            case "b2" :
                V.nav.back();
                break;
        }
    }
    
    @Override
    public void openDialog() {
        EscolherTipoPessoa np = new EscolherTipoPessoa();
    }

    
    public void loadPersonList(String filter, String tipo){
        panel.removeAll();
        if(!tipo.equals("back")){
            this.tipo = tipo;
            entity.setText(tipo + "");
        }
        
        
        personList = PessoaDB.getAll(tipo);
        int y = 0;
        for(int i = 0; i < personList.size(); i++){
            String n = personList.get(i).getNome1() + " " + personList.get(i).getNome2() + personList.get(i).getId();
            if(filter.equals("") || n.toLowerCase().indexOf(filter.toLowerCase()) > -1){
                ItemList pf = new ItemList(personList.get(i));
                panel.add(pf);
                pf.setVisible(true);
                pf.setLocation(0, y);
                y = y + 42;
                pf.setPreferredSize(new Dimension(1250,42));
                pf.setSize(new Dimension(1250,42));
                panel.setPreferredSize(new Dimension(1250,y));
                panel.setSize(new Dimension(1250,y));
            }
        }
        
        ss.updateSize();
        ss.resetPosition();
        panel.repaint();
        panel.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        porteLabel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        acoesLabel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        entity = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        entityPanel = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        shadow = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        searchBar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        scroll = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeLabel.setBackground(new java.awt.Color(255, 255, 255));
        nomeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nomeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nomeLabelMouseExited(evt);
            }
        });
        nomeLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/icons/angryimg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        nomeLabel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(15, 59, 146));
        jLabel3.setText("Nome");
        nomeLabel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel3.add(nomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 214, 30));

        porteLabel.setBackground(new java.awt.Color(255, 255, 255));
        porteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                porteLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                porteLabelMouseExited(evt);
            }
        });
        porteLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(15, 59, 146));
        jLabel6.setText("Cidade");
        porteLabel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/icons/angryimg.png"))); // NOI18N
        jLabel8.setText("jLabel1");
        porteLabel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2, -1));

        jPanel3.add(porteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 0, 450, 30));

        acoesLabel.setBackground(new java.awt.Color(255, 255, 255));
        acoesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acoesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                acoesLabelMouseExited(evt);
            }
        });
        acoesLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/icons/angryimg.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        acoesLabel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(15, 59, 146));
        jLabel4.setText("Ações");
        acoesLabel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel3.add(acoesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 0, 330, 30));

        entity.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        entity.setForeground(new java.awt.Color(80, 176, 230));
        entity.setText("Entity");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entityPanel.setBorder(null);
        entityPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        entityPanel.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                entityPanelMouseWheelMoved(evt);
            }
        });

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setPreferredSize(new java.awt.Dimension(668, 200));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        entityPanel.setViewportView(panel);

        jPanel1.add(entityPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 410));

        shadow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/shadow4.png"))); // NOI18N
        jPanel1.add(shadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 780, 100));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBar.setBorder(null);
        jPanel2.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 2, 240, 35));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/buscar0.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 42, 42));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/Box.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/Box.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 120, -1));

        scroll.setOpaque(false);

        javax.swing.GroupLayout scrollLayout = new javax.swing.GroupLayout(scroll);
        scroll.setLayout(scrollLayout);
        scrollLayout.setHorizontalGroup(
            scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        scrollLayout.setVerticalGroup(
            scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entity, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(entity))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeLabelMouseExited
        nomeLabel.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_nomeLabelMouseExited

    private void nomeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeLabelMouseEntered
        nomeLabel.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_nomeLabelMouseEntered

    private void porteLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porteLabelMouseExited
        porteLabel.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_porteLabelMouseExited

    private void porteLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porteLabelMouseEntered
        porteLabel.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_porteLabelMouseEntered

    private void acoesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acoesLabelMouseExited
        acoesLabel.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_acoesLabelMouseExited

    private void acoesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acoesLabelMouseEntered
        acoesLabel.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_acoesLabelMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadPersonList(searchBar.getText(), this.tipo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void entityPanelMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_entityPanelMouseWheelMoved
        ss.scroolAction(entityPanel.getVerticalScrollBar().getValue());
    }//GEN-LAST:event_entityPanelMouseWheelMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acoesLabel;
    private javax.swing.JLabel entity;
    private javax.swing.JScrollPane entityPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel nomeLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel porteLabel;
    private javax.swing.JPanel scroll;
    private javax.swing.JTextField searchBar;
    private javax.swing.JLabel shadow;
    // End of variables declaration//GEN-END:variables
}
