package gestaopet.components;

import gestaopet.V;
import gestaopet.classes.DateTools;
import gestaopet.classes.ModalPanel;
import gestaopet.enums.DateMethods;
import gestaopet.tema.ComboBox.ComboBox;
import gestaopet.tema.field.Field;
import java.awt.Component;
import java.awt.Dimension;
import java.util.Date;
import javax.swing.JTextField;

public class DataPicker extends ModalPanel {
    private Date data;
    private boolean dataDefinida = false;
    private JTextField j;
    private Field f;
    private String confirm;
    private Dimension d = new Dimension(325,140);
    public DataPicker() {
        initComponents();
        setPreferredSize(d);
        setSize(d);
        loadYear();
        loadDays();
        start();
        //parent = V.newPopUp(this);
    }
    
    public DataPicker(JTextField j) {
        this.j = j;
        initComponents();
        setPreferredSize(d);
        setSize(d);
        loadYear();
        loadDays();
        
        //parent = V.newPopUp(this);
        setInput(DateTools.dateToString(DateTools.getDate(DateMethods.TODAY, 0, 0, 0)));
        start();
    }
    
    public DataPicker(Field f, String confirm) {
        this.f = f;
        initComponents();
        setPreferredSize(d);
        setSize(d);
        loadYear();
        loadDays();
        //parent = V.newPopUp(this);
        setInput(DateTools.dateToString(DateTools.getDate(DateMethods.TODAY, 0, 0, 0)));
        this.confirm = confirm;
        start();
    }
    

    public String getData(){
        if(dataDefinida){
           return DateTools.dateToString(data);
        } else {
           return "";
        }
    }

    public void setInput(String data){
        
        String[] dt = data.split("/");
        int d = Integer.parseInt(dt[0]);
        int m = Integer.parseInt(dt[1]);
        String y = dt[2];
        
        for(int i = 0; i < year.getItemCount(); i++){
            String y2 = year.getItemAt(i);
            if(y2.equals(y)){
                year.setSelectedIndex(i);
            }
        }
        month.setSelectedIndex(m-1);
        day.setSelectedIndex(d-1);
    }


    
    public int year(){
        return Integer.parseInt((String)year.getSelectedItem());
    }
    
    public int month(){
        return month.getSelectedIndex() + 1;
    }

    public int day(){
        return Integer.parseInt((String)day.getSelectedItem());
    }
    
    private void loadYear(){
        int y = DateTools.getYear()+10;
        
        for(int i = 0; i < y - 1995; i++){
            year.addItem((1995 + i) + "");
        }
    }
    
    private void loadDays(){
        day.setSize(50, HEIGHT);
        day.removeAllItems();
        int[] days = DateTools.getDaysInMonth(year(), month());
        for(int i = 0; i < days.length; i++){
            day.addItem(days[i] + "");
        }
    }
    
    public void confirm(){
        data = DateTools.getDate(DateMethods.NEWDAY, year(), month(), day());
        dataDefinida = true;
        
        try {
            j.setText(DateTools.dateToString(data));
            j.firePropertyChange(accessibleContext.ACCESSIBLE_TEXT_PROPERTY, false, true);
        } catch (Exception e) {
            f.setText(DateTools.dateToString(data));
            f.onClick(confirm);
        }
        close();
    }
    
    public void cancel(){
        dataDefinida = false;
        close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        setName("10"); // NOI18N

        day.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        day.setForeground(new java.awt.Color(15, 59, 146));
        day.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 59, 146), 1, true));
        day.setMaximumSize(new java.awt.Dimension(72, 50));
        day.setMinimumSize(new java.awt.Dimension(72, 50));
        day.setName("dia"); // NOI18N
        day.setPreferredSize(new java.awt.Dimension(72, 50));

        month.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        month.setForeground(new java.awt.Color(15, 59, 146));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" }));
        month.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 59, 146), 1, true));
        month.setName("mes"); // NOI18N
        month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthItemStateChanged(evt);
            }
        });

        year.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        year.setForeground(new java.awt.Color(15, 59, 146));
        year.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 59, 146), 1, true));
        year.setName("ano"); // NOI18N
        year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearItemStateChanged(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/cancelarP0.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestaopet/tema/icons/confirmarP0.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(98, 98, 98)
                        .addComponent(jButton2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void monthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthItemStateChanged
        loadDays();
    }//GEN-LAST:event_monthItemStateChanged

    private void yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearItemStateChanged
        loadDays();
    }//GEN-LAST:event_yearItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        confirm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cancel();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
