package gestaopet.view.New.financeiro;

import gestaopet.classes.DateTools;
import gestaopet.classes.FinanceiroItem;
import gestaopet.classes.GlobalPanel;
import gestaopet.classes.InputTools;

public class PendencyItemList extends GlobalPanel {

    private FinanceiroItem financeiroItem;

    public PendencyItemList(FinanceiroItem financeiroItem) {
        initComponents();
        this.financeiroItem = financeiroItem;
        setAll();
    }

    public void setAll() {
        tabelaOrigemLabel1.setText(financeiroItem.getTabelaOrigem());
        quantidadeLabel.setText(financeiroItem.getQuantidade() + "");
        valorLabel.setText(InputTools.getStringValor(financeiroItem.getValor()));
        dataLabel.setText(DateTools.dateToString(financeiroItem.getData()));
        pessoaLabel.setText(financeiroItem.getPessoa());
        descricaoLabel.setText(financeiroItem.getDescricao());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantidadeLabel = new javax.swing.JLabel();
        descricaoLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        pessoaLabel = new javax.swing.JLabel();
        tabelaOrigemLabel1 = new javax.swing.JLabel();
        select = new javax.swing.JCheckBox();
        valorLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quantidadeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        quantidadeLabel.setText("Quantidade");
        add(quantidadeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 100, 20));

        descricaoLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        descricaoLabel.setText("Descricao");
        add(descricaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 180, 20));

        valorLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        valorLabel.setText("Valor");
        add(valorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 10, 70, 20));

        dataLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dataLabel.setText("Data");
        add(dataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 80, 20));

        pessoaLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pessoaLabel.setText("Pessoa");
        add(pessoaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 200, 20));

        tabelaOrigemLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tabelaOrigemLabel1.setText("Tabela Origem");
        add(tabelaOrigemLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        select.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        select.setIconTextGap(0);
        select.setMargin(new java.awt.Insets(11, 11, 11, 11));
        add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 40, 40));

        valorLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        valorLabel1.setText("R$");
        add(valorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseEvent(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        mouseEvent(evt);
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JLabel pessoaLabel;
    private javax.swing.JLabel quantidadeLabel;
    public javax.swing.JCheckBox select;
    private javax.swing.JLabel tabelaOrigemLabel1;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JLabel valorLabel1;
    // End of variables declaration//GEN-END:variables
}
