package gestaopet.classes;

import gestaopet.GestaoPet;
import gestaopet.V;
import gestaopet.components.modal.SpecialModal;
import gestaopet.components.modal.Blackout;
import java.awt.Dimension;
import java.awt.Window;

public class ModalPanel extends javax.swing.JPanel {
    public Blackout bo;
    private SpecialModal parent;

    public ModalPanel() {
        bo = new Blackout(this);
        initComponents();
        setDefaultLocale(null);
    }

    public void show(boolean show){

        parent.setVisible(show);
        bo.show(show);
        bringToFront();
    }
    
    public void setParentSize(Dimension d){
        parent.setPreferredSize(d);
        parent.setSize(d);
    }
    
    public void setParentPosition(int x, int y){
        parent.setLocation(x, y);
    }
    
    public void start(){
        parent = V.newSpecialModal(this, true);
        parent.setAlwaysOnTop(true);
        themeApply();
    }
    
    public void blackoutClose(){
        bo.close();
    }
    
    public void themeApply(){
        
    }
    
    public void close(){
        parent.close();
        blackoutClose();
    }
    
    public void bringToFront(){
        parent.bringToFront();
    }
    
    public void setInput(String input){
        System.out.println("Configure o método da classe herdeira");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
