package gestaopet.obsoletos;

import gestaopet.V;
import gestaopet.classes.DateTools;
import gestaopet.classes.ModalPanel;
import gestaopet.enums.DateMethods;
import java.awt.Dimension;
import java.util.Date;

public class DataPicker_OLD extends ModalPanel {
    //private PopUp parent;
    
    public DataPicker_OLD() {
        initComponents();
        Dimension d = new Dimension(325,165);
        setPreferredSize(d);
        setSize(d);
        loadYear();
        loadDays();
        start();
        //parent = V.newPopUp(this);
    }

    

    
    public int year(){
        return Integer.parseInt((String)year.getSelectedItem());
    }
    
    public int month(){
        return month.getSelectedIndex() + 1;
    }

    public int day(){
        return Integer.parseInt((String)day.getSelectedItem());
    }
    
    private void loadYear(){
        int y = DateTools.getYear();
        
        for(int i = 0; i < y - 1995; i++){
            year.addItem((1995 + i) + "");
        }
    }
    
    private void loadDays(){
        day.setSize(50, HEIGHT);
        day.removeAllItems();
        int[] days = DateTools.getDaysInMonth(year(), month());
        for(int i = 0; i < days.length; i++){
            day.addItem(days[i] + "");
        }
    }
    
    public void confirm(){
        Date d = DateTools.getDate(DateMethods.NEWDAY, year(), month(), day());
        V.petReg.setDate(d);
        close();
    }
    
    public void cancel(){
        close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        setName("10"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        day.setMaximumSize(new java.awt.Dimension(72, 50));
        day.setMinimumSize(new java.awt.Dimension(72, 50));
        day.setPreferredSize(new java.awt.Dimension(72, 50));
        add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" }));
        month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthItemStateChanged(evt);
            }
        });
        add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 10, 120, 50));

        year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearItemStateChanged(evt);
            }
        });
        add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 99, 50));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 99, 50));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Confirmar");
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 99, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void monthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthItemStateChanged
        loadDays();
    }//GEN-LAST:event_monthItemStateChanged

    private void yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearItemStateChanged
        loadDays();
    }//GEN-LAST:event_yearItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        confirm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cancel();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
